[package]
name = "pacup"
version = "1.0.0"
edition = "2021"
authors = [
    "Nathan Kolpa"
]

[profile.release]
debug = false
strip = true
codegen-units = 1
lto = true

[dependencies]
clap = { version = "4.3.4", features = ["derive"] }
libc = "0.2.146"
